In [1]:
import pandas as pd
import os
import ssl
import json
import http.client
import sqlite3 as sql

# Set up Connection String

In [37]:
conn = http.client.HTTPSConnection("v3.football.api-sports.io")

headers = {
    'x-rapidapi-host': "v3.football.api-sports.io",
    'x-rapidapi-key': "a8c37a21a0a74ea9bf50000cd74320fb"
    }

### Make Request and store into variable my JSON Variable

In [3]:
conn.request("GET", "/players/squads?team=1615", headers=headers)

res = conn.getresponse()
data = res.read()

my_json = data.decode('utf-8')

### Print to see if it worked

In [4]:
data = json.loads(my_json)
s = json.dumps(data, indent=4, sort_keys=True)
print(s)

{
    "errors": [],
    "get": "players/squads",
    "paging": {
        "current": 1,
        "total": 1
    },
    "parameters": {
        "team": "1615"
    },
    "response": [
        {
            "players": [
                {
                    "age": 29,
                    "id": 64165,
                    "name": "J. Kempin",
                    "number": 21,
                    "photo": "https://media.api-sports.io/football/players/64165.png",
                    "position": "Goalkeeper"
                },
                {
                    "age": 32,
                    "id": 50752,
                    "name": "B. Hamid",
                    "number": 28,
                    "photo": "https://media.api-sports.io/football/players/50752.png",
                    "position": "Goalkeeper"
                },
                {
                    "age": 24,
                    "id": 129929,
                    "name": "L. Zamudio",
                    "number": 50,
                    "photo": "https://media.api-sports.io/football/players/129929.png",
                    "position": "Goalkeeper"
                },
                {
                    "age": 32,
                    "id": 2438,
                    "name": "R. Romo",
                    "number": null,
                    "photo": "https://media.api-sports.io/football/players/2438.png",
                    "position": "Goalkeeper"
                },
                {
                    "age": 25,
                    "id": 135800,
                    "name": "Gaoussou Samake",
                    "number": 2,
                    "photo": "https://media.api-sports.io/football/players/135800.png",
                    "position": "Defender"
                },
                {
                    "age": 27,
                    "id": 50759,
                    "name": "C. Odoi-Atsem",
                    "number": 3,
                    "photo": "https://media.api-sports.io/football/players/50759.png",
                    "position": "Defender"
                },
                {
                    "age": 28,
                    "id": 8527,
                    "name": "B. Hines-Ike",
                    "number": 4,
                    "photo": "https://media.api-sports.io/football/players/8527.png",
                    "position": "Defender"
                },
                {
                    "age": 28,
                    "id": 51106,
                    "name": "B. Smith",
                    "number": 5,
                    "photo": "https://media.api-sports.io/football/players/51106.png",
                    "position": "Defender"
                },
                {
                    "age": 29,
                    "id": 1415,
                    "name": "A. Najar",
                    "number": 14,
                    "photo": "https://media.api-sports.io/football/players/1415.png",
                    "position": "Defender"
                },
                {
                    "age": 31,
                    "id": 50754,
                    "name": "S. Birnbaum",
                    "number": 15,
                    "photo": "https://media.api-sports.io/football/players/50754.png",
                    "position": "Defender"
                },
                {
                    "age": 20,
                    "id": 71249,
                    "name": "Hayden Sargis",
                    "number": 20,
                    "photo": "https://media.api-sports.io/football/players/71249.png",
                    "position": "Defender"
                },
                {
                    "age": 24,
                    "id": 50760,
                    "name": "Donovan Pines",
                    "number": 23,
                    "photo": "https://media.api-sports.io/football/players/50760.png",
                    "position": "Defender"
                },
                {
                    "age": 29,
                    "id": 50883,
                    "name": "J. Gressel",
                    "number": 31,
                    "photo": "https://media.api-sports.io/football/players/50883.png",
                    "position": "Defender"
                },
                {
                    "age": 19,
                    "id": 119007,
                    "name": "Jacob Greene",
                    "number": 33,
                    "photo": "https://media.api-sports.io/football/players/119007.png",
                    "position": "Defender"
                },
                {
                    "age": 29,
                    "id": 206985,
                    "name": "J. Alfaro",
                    "number": 93,
                    "photo": "https://media.api-sports.io/football/players/206985.png",
                    "position": "Defender"
                },
                {
                    "age": 27,
                    "id": 50764,
                    "name": "R. Canouse",
                    "number": 6,
                    "photo": "https://media.api-sports.io/football/players/50764.png",
                    "position": "Midfielder"
                },
                {
                    "age": 22,
                    "id": 50756,
                    "name": "C. Durkin",
                    "number": 8,
                    "photo": "https://media.api-sports.io/football/players/50756.png",
                    "position": "Midfielder"
                },
                {
                    "age": 28,
                    "id": 2429,
                    "name": "E. Flores",
                    "number": 10,
                    "photo": "https://media.api-sports.io/football/players/2429.png",
                    "position": "Midfielder"
                },
                {
                    "age": 27,
                    "id": 71254,
                    "name": "Drew Skundrich",
                    "number": 12,
                    "photo": "https://media.api-sports.io/football/players/71254.png",
                    "position": "Midfielder"
                },
                {
                    "age": 23,
                    "id": 351492,
                    "name": "S. Djeffal",
                    "number": 13,
                    "photo": "https://media.api-sports.io/football/players/351492.png",
                    "position": "Midfielder"
                },
                {
                    "age": 19,
                    "id": 119006,
                    "name": "Jeremy Garay",
                    "number": 18,
                    "photo": "https://media.api-sports.io/football/players/119006.png",
                    "position": "Midfielder"
                },
                {
                    "age": 20,
                    "id": 50774,
                    "name": "Griffin McDorman Yow",
                    "number": 22,
                    "photo": "https://media.api-sports.io/football/players/50774.png",
                    "position": "Midfielder"
                },
                {
                    "age": 24,
                    "id": 208363,
                    "name": "Azaad Liadi",
                    "number": 24,
                    "photo": "https://media.api-sports.io/football/players/208363.png",
                    "position": "Midfielder"
                },
                {
                    "age": 18,
                    "id": 323776,
                    "name": "Jackson Hopkins",
                    "number": 25,
                    "photo": "https://media.api-sports.io/football/players/323776.png",
                    "position": "Midfielder"
                },
                {
                    "age": 19,
                    "id": 71115,
                    "name": "Moses Nyeman",
                    "number": 27,
                    "photo": "https://media.api-sports.io/football/players/71115.png",
                    "position": "Midfielder"
                },
                {
                    "age": 20,
                    "id": 71110,
                    "name": "Theodore Ku-Dipietro",
                    "number": 35,
                    "photo": "https://media.api-sports.io/football/players/71110.png",
                    "position": "Midfielder"
                },
                {
                    "age": 19,
                    "id": 51268,
                    "name": "Tyler Freeman",
                    "number": null,
                    "photo": "https://media.api-sports.io/football/players/51268.png",
                    "position": "Midfielder"
                },
                {
                    "age": 26,
                    "id": 16432,
                    "name": "M. Estrada",
                    "number": 7,
                    "photo": "https://media.api-sports.io/football/players/16432.png",
                    "position": "Attacker"
                },
                {
                    "age": 33,
                    "id": 12888,
                    "name": "O. Kamara",
                    "number": 9,
                    "photo": "https://media.api-sports.io/football/players/12888.png",
                    "position": "Attacker"
                },
                {
                    "age": 27,
                    "id": 7625,
                    "name": "T. Fountas",
                    "number": 11,
                    "photo": "https://media.api-sports.io/football/players/7625.png",
                    "position": "Attacker"
                },
                {
                    "age": 27,
                    "id": 51042,
                    "name": "A. Perez",
                    "number": 16,
                    "photo": "https://media.api-sports.io/football/players/51042.png",
                    "position": "Attacker"
                },
                {
                    "age": 24,
                    "id": 307571,
                    "name": "K. Smith",
                    "number": 17,
                    "photo": "https://media.api-sports.io/football/players/307571.png",
                    "position": "Attacker"
                },
                {
                    "age": 24,
                    "id": 37054,
                    "name": "N. Robertha",
                    "number": 19,
                    "photo": "https://media.api-sports.io/football/players/37054.png",
                    "position": "Attacker"
                }
            ],
            "team": {
                "id": 1615,
                "logo": "https://media.api-sports.io/football/teams/1615.png",
                "name": "DC United"
            }
        }
    ],
    "results": 1
}

In [5]:
pd.json_normalize(data)

,get,errors,results,response,parameters.team,paging.current,paging.total
0,players/squads,[],1,"[{'team': {'id': 1615, 'name': 'DC United', 'l...",1615,1,1

In [6]:
df_nested = pd.json_normalize(data, record_path = ['response'])

# df_nested = pd.json_normalize(data, record_path = ['response'], max_level = 2)

In [7]:
df_nested.info()

df_nested['players']

df_nested2 = pd.json_normalize(df_nested.players[0])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   players    1 non-null      object
 1   team.id    1 non-null      int64
 2   team.name  1 non-null      object
 3   team.logo  1 non-null      object
dtypes: int64(1), object(3)
memory usage: 160.0+ bytes

In [12]:
df_nested2

,id,name,age,number,position,photo
0,64165,J. Kempin,29,21.0,Goalkeeper,https://media.api-sports.io/football/players/6...
1,50752,B. Hamid,32,28.0,Goalkeeper,https://media.api-sports.io/football/players/5...
2,129929,L. Zamudio,24,50.0,Goalkeeper,https://media.api-sports.io/football/players/1...
3,2438,R. Romo,32,NaN,Goalkeeper,https://media.api-sports.io/football/players/2...
4,135800,Gaoussou Samake,25,2.0,Defender,https://media.api-sports.io/football/players/1...
5,50759,C. Odoi-Atsem,27,3.0,Defender,https://media.api-sports.io/football/players/5...
6,8527,B. Hines-Ike,28,4.0,Defender,https://media.api-sports.io/football/players/8...
7,51106,B. Smith,28,5.0,Defender,https://media.api-sports.io/football/players/5...
8,1415,A. Najar,29,14.0,Defender,https://media.api-sports.io/football/players/1...
9,50754,S. Birnbaum,31,15.0,Defender,https://media.api-sports.io/football/players/5...
10,71249,Hayden Sargis,20,20.0,Defender,https://media.api-sports.io/football/players/7...
11,50760,Donovan Pines,24,23.0,Defender,https://media.api-sports.io/football/players/5...
12,50883,J. Gressel,29,31.0,Defender,https://media.api-sports.io/football/players/5...
13,119007,Jacob Greene,19,33.0,Defender,https://media.api-sports.io/football/players/1...
14,206985,J. Alfaro,29,93.0,Defender,https://media.api-sports.io/football/players/2...
15,50764,R. Canouse,27,6.0,Midfielder,https://media.api-sports.io/football/players/5...
16,50756,C. Durkin,22,8.0,Midfielder,https://media.api-sports.io/football/players/5...
17,2429,E. Flores,28,10.0,Midfielder,https://media.api-sports.io/football/players/2...
18,71254,Drew Skundrich,27,12.0,Midfielder,https://media.api-sports.io/football/players/7...
19,351492,S. Djeffal,23,13.0,Midfielder,https://media.api-sports.io/football/players/3...
20,119006,Jeremy Garay,19,18.0,Midfielder,https://media.api-sports.io/football/players/1...
21,50774,Griffin McDorman Yow,20,22.0,Midfielder,https://media.api-sports.io/football/players/5...
22,208363,Azaad Liadi,24,24.0,Midfielder,https://media.api-sports.io/football/players/2...
23,323776,Jackson Hopkins,18,25.0,Midfielder,https://media.api-sports.io/football/players/3...
24,71115,Moses Nyeman,19,27.0,Midfielder,https://media.api-sports.io/football/players/7...
25,71110,Theodore Ku-Dipietro,20,35.0,Midfielder,https://media.api-sports.io/football/players/7...
26,51268,Tyler Freeman,19,NaN,Midfielder,https://media.api-sports.io/football/players/5...
27,16432,M. Estrada,26,7.0,Attacker,https://media.api-sports.io/football/players/1...
28,12888,O. Kamara,33,9.0,Attacker,https://media.api-sports.io/football/players/1...
29,7625,T. Fountas,27,11.0,Attacker,https://media.api-sports.io/football/players/7...
30,51042,A. Perez,27,16.0,Attacker,https://media.api-sports.io/football/players/5...
31,307571,K. Smith,24,17.0,Attacker,https://media.api-sports.io/football/players/3...
32,37054,N. Robertha,24,19.0,Attacker,https://media.api-sports.io/football/players/3...

In [38]:
# conn.request("GET", "/teams/statistics?season=2020&team=42&league=39", headers=headers)
# Get historical data

for x in range(2010, 2022):

    conn.request("GET", "/teams/statistics?season={}&team=1615&league=253".format(x), headers=headers)

    res = conn.getresponse()
    data = res.read()

    my_json = (data.decode("utf-8"))

    data = json.loads(my_json)
    s = json.dumps(data, indent=4, sort_keys=True)

    df_team = pd.json_normalize(data, max_level=1)

    df_team2 = pd.json_normalize(df_team['response.fixtures'][0])

    df_team2['season'] = x
    
    df_team2['points_at_home'] = df_team2['wins.home']*3 + df_team2['draws.home']
    df_team2['points_away'] = df_team2['wins.away']*3 + df_team2['draws.away']
    df_team2['points_total'] = df_team2['wins.total']*3 + df_team2['draws.total']

    df_team2.to_sql('Season_Results_2', conn_db, if_exists='append')

In [15]:
# data = json.loads(my_json)
# s = json.dumps(data, indent=4, sort_keys=True)
# # print(s)

In [16]:
# df_team = pd.json_normalize(data, max_level=1)

In [17]:
df_team.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   get                       1 non-null      object
 1   errors                    1 non-null      object
 2   results                   1 non-null      int64
 3   parameters.season         1 non-null      object
 4   parameters.team           1 non-null      object
 5   parameters.league         1 non-null      object
 6   paging.current            1 non-null      int64
 7   paging.total              1 non-null      int64
 8   response.league           1 non-null      object
 9   response.team             1 non-null      object
 10  response.form             1 non-null      object
 11  response.fixtures         1 non-null      object
 12  response.goals            1 non-null      object
 13  response.biggest          1 non-null      object
 14  response.clean_sheet      1 non-null      object
 15  response.failed_to_score  1 non-null      object
 16  response.penalty          1 non-null      object
 17  response.lineups          1 non-null      object
 18  response.cards            1 non-null      object
dtypes: int64(3), object(16)
memory usage: 280.0+ bytes

In [18]:
df_team2 = pd.json_normalize(df_team['response.fixtures'][0])

In [19]:
df_team2['season'] = Year

NameError: name 'Year' is not defined

In [20]:
df_team2['points_at_home'] = df_team2['wins.home']*3 + df_team2['draws.home']
df_team2['points_away'] = df_team2['wins.away']*3 + df_team2['draws.away']
df_team2['points_total'] = df_team2['wins.total']*3 + df_team2['draws.total']

df_team2

,played.home,played.away,played.total,wins.home,wins.away,wins.total,draws.home,draws.away,draws.total,loses.home,loses.away,loses.total,points_at_home,points_away,points_total
0,12,11,23,2,3,5,4,2,6,6,6,12,10,11,21

In [44]:
conn_db = sql.connect('DcUnited_season.db')

In [ ]:
df_team2.to_sql('Season_Results_2', conn_db, if_exists='append')

In [47]:
Database_DF = pd.read_sql('SELECT * FROM Season_Results_2', conn_db)

In [46]:
# sql = 'DELETE FROM Season_Results_2 WHERE season=2022'
# conn_db.execute(sql)
# conn_db.commit()

In [48]:
Database_DF

,index,played.home,played.away,played.total,wins.home,wins.away,wins.total,draws.home,draws.away,draws.total,loses.home,loses.away,loses.total,season,points_at_home,points_away,points_total
0,0,0,0,0,0,0,0,0,0,0,0,0,0,2010,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,2011,0,0,0
2,0,19,19,38,12,6,18,6,3,9,1,10,11,2012,42,21,63
3,0,17,17,34,3,0,3,4,3,7,10,14,24,2013,13,3,16
4,0,18,18,36,12,6,18,4,4,8,2,8,10,2014,40,22,62
5,0,19,18,37,12,4,16,3,3,6,4,11,15,2015,39,15,54
6,0,18,17,35,9,2,11,4,9,13,5,6,11,2016,31,15,46
7,0,17,17,34,6,3,9,3,2,5,8,12,20,2017,21,11,32
8,0,18,17,35,13,1,14,3,7,10,2,9,11,2018,42,10,52
9,0,17,18,35,7,6,13,6,5,11,4,7,11,2019,27,23,50
10,0,19,18,37,12,4,16,3,3,6,4,11,15,2015,39,15,54
11,0,18,17,35,9,2,11,4,9,13,5,6,11,2016,31,15,46
12,0,17,17,34,6,3,9,3,2,5,8,12,20,2017,21,11,32
13,0,18,17,35,13,1,14,3,7,10,2,9,11,2018,42,10,52
14,0,17,18,35,7,6,13,6,5,11,4,7,11,2019,27,23,50
15,0,12,11,23,2,3,5,4,2,6,6,6,12,2020,10,11,21
16,0,17,17,34,11,3,14,1,4,5,5,10,15,2021,34,13,47

In [41]:
Database_DF = Database_DF.drop('index', axis=1)

In [42]:
Database_DF = pd.melt(Database_DF, id_vars = ['season'])

Cannot connect directly to Tab Public using a sql database. A workaround is to export the dataframe into a google sheet

In [43]:
# path="C:Users/612540/Downloads/Combined_Book.csv"


file_name = 'file.csv'

Database_DF.to_csv(r"C:\Users\612540\Downloads\DcUnitedStats.csv", encoding='utf-8', index=False)